name: unittest

on:
    workflow_dispatch:
    push:
    pull_request:

jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v3.3.0
                with:
                    fetch-depth: 0
            
            -   name: Install Dependencies
                run: python3 -m pip install -r requirements.txt
            
            -   name: Execute Unit Tests
                run: python3 -m unittest discover test/
